### ISSUE TITLE
Multi_core/thread support 

### ISSUE THREAD

**Issue by akhst7** [TomKellyGenetics/leiden#21]
I am tryint to generate leiden clusters based on Seurat integrated obj, (3000, 99192) converted to a SingleCellExperiment obj.  I run  following lines to generate the leiden cluster:

```
g <- buildSNNGraph(sce, k=10, use.dimred="PCA" ,BPPARAM=MulticoreParam(40), type="jaccard")
g.am<-as_adjacency_matrix(g)
g.am
99192 x 99192 sparse Matrix of class "dgCMatrix"
partition<-leiden(g.am)
```
The whole process took about an hour.  Is there any way to speed this process up, perhaps  by incorporating a multi thread support ? 

Thanks.

**Comment by jsim91** [comment]
Many clustering algorithms understandably have trouble partitioning large datasets quickly. There are clustering packages that are geared toward datasets with 10s of millions of events. One that I know of is `FastPG` (https://github.com/sararselitsky/FastPG). The Nolan lab used this clustering algorithm in their recent publication **Human influenza virus challenge identifies cellular correlates of protection for oral vaccination (2021)** to cluster a cytof dataset that was 27M cells long and 43 antibodies wide. FastPG makes use of parallel computing (hence the "Fast" part).

The problem with FastPG (depending on who you ask) is that it gives results that are not fully reproducible **because** it's run in parallel. See here for more on this issue: [FastPG - issue 16](https://github.com/sararselitsky/FastPG/issues/16). Furthermore, FastPG makes use of the Grappolo algorithm which can be described as a parallel Louvain community detection algorithm. Since Seurat already has a louvain option for clustering you likely wouldn't be interested in FastPG anyway.

The leiden package authors can correct me if I'm wrong here but as I understand it, the leiden algorithm has to be run in a serial, or sequential, mode. I'm stealing a few lines from the leiden publication that describe the algorithm in concept:

> The Leiden algorithm consists of three phases: (1) local moving of nodes, (2) refinement of the partition and (3) aggregation of the network based on the refined partition, using the non-refined partition to create an initial partition for the aggregate network

It would seem that each iteration depends on the previous iteration's result. This schema just doesn't lend itself to parallel computing.

**Comment by akhst7** [comment]
@jsim91 ,  thanks for a thorough explanation.  I guess demential reduction algorithms such as UMAP are facing  the similar issue with parallel processing even setting setseed.   Anyway, I will try FastPG and see what. Otherwise, I will run Leiden through  the Arm64 in Mac or AWS.
