### ISSUE TITLE
jgraph error

### ISSUE THREAD

**Issue by r3fang** [TomKellyGenetics/leiden#6]
Hi running Leidan, I got this error:

```
Error in py_module_import(module, convert = convert) :
  DeprecationWarning: To avoid name collision with the igraph project, this visualization library has been renamed to 'jgraph'. Please upgrade when convenient.

Detailed traceback:
  File "/home/r3fang/anaconda2/lib/python2.7/site-packages/leidenalg/__init__.py", line 35, in <module>
    from .functions import ALL_COMMS
  File "/home/r3fang/anaconda2/lib/python2.7/site-packages/leidenalg/functions.py", line 2, in <module>
    import igraph as _ig
  File "/home/r3fang/anaconda2/lib/python2.7/site-packages/igraph/__init__.py", line 8, in <module>
    raise DeprecationWarning("To avoid name collision with the igraph project, "
```

**Comment by r3fang** [comment]
solved by installing through CRAN

**Comment by TomKellyGenetics** [comment]
This occurs because leiden depends on the igraph project (version 0.7) which can be installed with `pip install python-igraph`. It clashes with the igraph 0.11.1 library (which has been renamed to jgraph). If you run into problems, I recommend installing the python dependencies first but the `.onLoad` function should set up the `r-reticulate` conda environment. I've provided details of setting it up in the benchmarking vignette in leiden version 0.3.0.

**Comment by TomKellyGenetics** [comment]
Further development will be done in the development branch to avoid these issues affecting the master branch.
